"""add forked_from_id to lists

Revision ID: 237bfc5290f0
Revises: 5af41d95728f
Create Date: 2026-08-01 03:10:54.665807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237bfc5290f0'
down_revision: Union[str, Sequence[str], None] = '5af41d95728f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('forked_from_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'lists', 'lists', ['forked_from_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lists', type_='foreignkey')
    op.drop_column('lists', 'forked_from_id')
    # ### end Alembic commands ###
